### PR TITLE
Use phantomjs library instead of grunt-lib-phantomjs

### PR DESCRIPTION
**Pull request by BYK**
Uses `phantomjs` library and uses it the recommended way instead of indirectly using the `phantom` binary inside `grunt-lib-phantomjs`. Apparently this project does not need the higher-level features of `grunt-lib-phantomjs` and this makes things easier and more robust (such as working on Windows etc.).

### CODE REVIEW

**Comment by jrcryer** [comment]
:+1: Can you squash your commits please?

**Comment by BYK** [comment]
> Can you squash your commits please?

I would but they really are separate commits. My bad since I opened the PR from master. Would you like me to get these on a separate branch?

**Comment by BYK** [comment]
> Would you like me to get these on a separate branch?

This would mean 3+ pull requests instead of one, which might make more sense :)

**Comment by jrcryer** [comment]
Take a look at: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request - You can still squash them.  If you run into trouble, let me know and we'll just merge it through.

**Comment by BYK** [comment]
I know how to use git but thank you :D

I'm trying to say I **can** squash these but I definitely think they should stay in separate commits and merging them will make it harder for any future developer to track back changes atomically. If you still want me to squash, I will though.

**Comment by jrcryer** [comment]
:+1:

**Pull request merged**
